version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  settings:
    staticcheck:
      checks:
        - all
        - -ST1005 # Allow capitalized error strings and punctuation

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
